#!/bin/bash
#
# Launch the server.  If necessary, do other things:
#   - unpack the current version
#   - shut down the previous version
#   - etc

# probably not the best choice
correct_user="nobody"

if ! test "${correct_user}" = "${USER}"; then
  echo "Warning:  Switching user to:  '${correct_user}'"
  exec sudo -u "${correct_user}" "${0}"
fi

function main() {
  # Read active version.
  read version < local/version
  if test '' = "${version}"; then
    fail "Failed to read a version string."
  fi
  unpack_dir="active/bedrock-server-${version}"
  # Unpack active version.
  if ! test -d "${unpack_dir}"; then
    mkdir "${unpack_dir}" || fail "Failed to create unpack directory:  '${unpack_dir}'"
    cd "${unpack_dir}" || fail "Failed to enter unpack directory:  '${unpack_dir}'"
    zip_file="${OLDPWD}/upstream/bedrock-server-${version}.zip"
    unzip "${zip_file}" || fail "Failed to unzip:  '${zip_file}'"
    cd - || fail "Failed to change directory back from the unpack directory."
  fi
  # Read active PID.
  if test -e active/pid; then
    read pid < active/pid
    # Stop active PID.
    if ps -p "${pid}" >/dev/null 2>&1; then
      kill "${pid}"
      dots "${pid}"
      if ps -p "${pid}" >/dev/null 2>&1; then
        kill -9 "${pid}"
        dots "${pid}"
        if ps -p "${pid}" >/dev/null 2>&1; then
          fail "Failed to kill PID:  '${pid}'"
        fi
      fi
    fi
    
  fi
  # Configure active version.
  cp local/conf/* "${unpack_dir}"/ || fail "Failed to copy configuration."
  if ! test -s "${unpack_dir}"/worlds; then
    mv "${unpack_dir}"/worlds "${unpack_dir}"/worlds_original  # Don't fail if the file is absent.
    ln -s ../worlds "${unpack_dir}"/worlds || fail "Failed to create symlink for worlds."
    mkdir -p "${unpack_dir}"/../worlds || fail "Failed to create worlds directory."
  fi
  # Start active version.
  if ! test -e active/commands; then
    mkfifo active/commands || fail "Failed to create named pipe for commands."
  fi
  echo
  echo
  echo "----------------------------"
  echo "STARTING INTERACTIVE SESSION"
  echo "----------------------------"
  echo
  echo
  echo 'Type "stop" to stop the server.'
  echo
  echo
  # It isn't actually interactive for just a moment, but hopefully that isn't noticeable.
  cd "${unpack_dir}"
  ./bedrock_server < "${OLDPWD}"/active/commands & pid="${!}"
  cd -
  # Write active PID.
  echo "${pid}" > active/pid
  # Establish interactive session.
  cat > active/commands

  # Execution should halt here until the user stops the server, the server
  # crashes, or the user ends or backgrounds the cat process.  Ending or
  # backgrounding the cat process should cause an apparent hang, as the wait
  # line below will not return until the server process ends.

  # Clean up.
  wait "${pid}"; ret="${?}"
  if ! test 0 = "${ret}"; then
    fail "Returned:  ${ret}"
  else
    echo "Returned:  ${ret}"
  fi
}


function dots() {
  pid="${1}"

  for i in $(seq 1 10); do
    if ! ps -p "${pid}" >/dev/null 2>&1; then
      break
    fi
    echo -n '.'
    sleep 1
  done
  echo
}


function error() {
  printf '%s\n' "ERROR:  ${1}" >&2
}


function fail() {
  error "${1}"
  exit "${2:-1}"
}


main
